-- aoALB first-site bootstrap
-- Run only after 202607190001_site_sharing.sql succeeds.
-- Change ONLY the single bootstrap_input VALUES row below.
-- The join code is generated by PostgreSQL and is shown once in the result.

begin;

create temp table bootstrap_input (
  admin_user_id uuid not null,
  site_code text not null,
  site_name text not null,
  device_name text not null
) on commit drop;

insert into bootstrap_input(admin_user_id, site_code, site_name, device_name)
values (
  '00000000-0000-0000-0000-000000000000', -- Authentication > Usersでコピーした初期管理者の匿名Auth UUID
  'CHANGE_ME',                              -- 3～40文字の英大文字・数字・_・-（利用者が入力する現場ID）
  'ここを現場名へ変更',                    -- 1～160文字
  'ここを端末名へ変更'                     -- 1～80文字
);

create temp table bootstrap_result (
  site_id uuid not null,
  site_code text not null,
  site_name text not null,
  admin_user_id uuid not null,
  initial_join_code text not null,
  note text not null
) on commit preserve rows;

do $bootstrap$
declare
  v_input pg_temp.bootstrap_input%rowtype;
  v_site_id uuid := pg_catalog.gen_random_uuid();
  v_join_code text := upper(encode(extensions.gen_random_bytes(8), 'hex'));
begin
  select * into strict v_input from pg_temp.bootstrap_input;

  if v_input.admin_user_id = '00000000-0000-0000-0000-000000000000'::uuid then
    raise exception 'admin_user_idを匿名Auth UUIDへ変更してください。';
  end if;
  if v_input.site_code = 'CHANGE_ME' then
    raise exception 'site_codeを変更してください。';
  end if;
  if upper(trim(v_input.site_code)) !~ '^[A-Z0-9][A-Z0-9_-]{2,39}$' then
    raise exception 'site_codeは3～40文字の英大文字・数字・_・-で指定してください。';
  end if;
  if char_length(trim(v_input.site_name)) not between 1 and 160 then
    raise exception 'site_nameは1～160文字で指定してください。';
  end if;
  if char_length(trim(v_input.device_name)) not between 1 and 80 then
    raise exception 'device_nameは1～80文字で指定してください。';
  end if;
  if not exists (
    select 1 from auth.users u
    where u.id = v_input.admin_user_id and coalesce(u.is_anonymous, false)
  ) then
    raise exception '指定UUIDの匿名Authユーザーが見つかりません。Anonymous Sign-In後のUUIDを確認してください。';
  end if;
  if exists (select 1 from public.sites s where s.site_code = upper(trim(v_input.site_code))) then
    raise exception '同じsite_codeの現場が既に存在します。';
  end if;
  if exists (select 1 from public.site_members m where m.user_id = v_input.admin_user_id and m.role = 'admin') then
    raise exception '指定ユーザーは既に管理者です。初回bootstrapの再実行を停止しました。';
  end if;

  insert into public.sites(id, site_code, name, created_by)
  values (v_site_id, upper(trim(v_input.site_code)), trim(v_input.site_name), v_input.admin_user_id);

  insert into public.site_join_codes(site_id, code_hash, grant_role, changed_by)
  values (
    v_site_id,
    extensions.crypt(v_join_code, extensions.gen_salt('bf', 10)),
    'editor',
    v_input.admin_user_id
  );

  insert into public.site_members(site_id, user_id, role, device_name)
  values (v_site_id, v_input.admin_user_id, 'admin', trim(v_input.device_name));

  insert into public.audit_logs(site_id, actor_user_id, action, entity_type, entity_id, details)
  values (v_site_id, v_input.admin_user_id, 'site.bootstrap', 'site', v_site_id, jsonb_build_object('method', 'sql_editor'));

  insert into pg_temp.bootstrap_result
  values (
    v_site_id,
    upper(trim(v_input.site_code)),
    trim(v_input.site_name),
    v_input.admin_user_id,
    v_join_code,
    'initial_join_codeはこの結果に一度だけ表示されます。安全な場所へ控えてください。DBにはハッシュだけを保存しました。'
  );
end
$bootstrap$;

commit;

select site_id, site_code, site_name, admin_user_id, initial_join_code, note
from pg_temp.bootstrap_result;

drop table pg_temp.bootstrap_result;
